version: '3'

services:
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
#      - /tmp/app/mysqld:/run/mysqld
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: Calculate_Sum
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - /tmp/app/mysqld:/var/run/mysqld
#      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"