# Generated by Django 3.2.5 on 2021-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('uniqueIndentifier', models.CharField(max_length=100)),
            ],
        ),
    ]
